install: fix rudra with --locked
error: failed to compile `rudra v0.1.0 (/home/runner/work/dockerfiles/dockerfiles/Rudra)`, intermediate artifacts can be found at `/home/runner/work/dockerfiles/dockerfiles/Rudra/target`
Caused by:
  package `libc v0.2.164` cannot be built because it requires rustc 1.63 or newer, while the currently active rustc version is 1.58.0-nightly